export const users = [
  {
    id: 'user-0',
    firstname: 'Ollie',
    lastname: 'Murphree',
    title: 'Mr.',
    dataOfBirth: '01/07/1970',
    employmentStatus: 'Full time',
    annualIncome: 34000,
    houseNumber: 700,
    postcode: 'BS14 9PR',
    image: '',
  },
  {
    id: 'user-1',
    firstname: 'Elizabeth',
    lastname: 'Edmundson',
    title: 'Miss',
    dataOfBirth: '29/06/1984',
    employmentStatus: 'Student',
    annualIncome: 17000,
    houseNumber: 177,
    postcode: 'PH12 8UW',
    image: '',
  },
  {
    id: 'user-2',
    firstname: 'Trevor',
    lastname: 'Rieck',
    title: 'Mr.',
    dataOfBirth: '07/09/1990',
    employmentStatus: 'Part time',
    annualIncome: 15000,
    houseNumber: 343,
    postcode: 'TS25 2NF',
    image: '',
  },
];
